### ISSUE TITLE
make letters to keep contrast when shift to dark theme

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/epiversetheme#19]
letter color seems not to change to create contrast from background.

![image](https://github.com/user-attachments/assets/0dd4d4f1-be08-4e56-bd11-94fea3cbc2d0)

![image](https://github.com/user-attachments/assets/41438a17-171a-4d24-b2a9-d8f1911e4214)

**Comment by Bisaloo** [comment]
I pushed a temporary fix in #20. A better long-term fix would probably be https://github.com/rstudio/DT/issues/1144.
