### ISSUE TITLE
increase the color contrast of the options button in the upper right corner

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/epiversetheme#2]
When I move the screen to half of the screen, the options button has little contrast, which limits the possibility of finding it. I thought it disappeared initially. The contrast in the cellphone has the same feature.

This is how it looks in https://epiverse-trace.github.io/finalsize/dev/

![image](https://github.com/epiverse-trace/epiversetheme/assets/21230390/a082bc85-6b5d-4f21-9eb9-eb857ef5e4a2)

This is how it looks in https://epiverse-trace.github.io/finalsize/

![image](https://github.com/epiverse-trace/epiversetheme/assets/21230390/c1bcd6af-a02a-461a-8dee-fcdfabeeabe8)

**Comment by Bisaloo** [comment]
Thanks for the reports @avallecam & @adamkucharski!

This is now fixed in https://github.com/epiverse-trace/epiversetheme/commit/e5e7070b6eb6c82f7c895b4f0b6a317d5c1ca9bb.
